---
- name: Enforce and revert SSH configuration #git url is https://github.com/abhigya03mukherjee/Ansible-Project
  hosts: all
  become: yes
  vars:
    ssh_config_path: /etc/ssh/sshd_config
    desired_ssh_setting: "PermitRootLogin no"

  tasks:

    - name: Check current SSH config
      command: grep "^PermitRootLogin" {{ ssh_config_path }}
      register: ssh_config
      changed_when: false
      failed_when: false

    - name: Revert SSH config if changed
      lineinfile:
        path: "{{ ssh_config_path }}"
        regexp: '^PermitRootLogin'
        line: "{{ desired_ssh_setting }}"
        backup: yes
      when: ssh_config.stdout != desired_ssh_setting
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted

